name: adhan_foreground_service
description: Native Adhan Foreground Service for HajiCare
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.hajicare.adhan
        pluginClass: AdhanForegroundPlugin
