name: hajicare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.2.1
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  vibration: ^2.0.0
  flutter_tts: ^4.2.2
  shared_preferences: ^2.5.5
  adhan: ^2.0.0+1
  flutter_compass: ^0.8.1
  geolocator: ^14.0.2
  hijri: ^3.0.1
  geocoding: ^5.0.0
  timezone: ^0.11.1
  lat_lng_to_timezone: ^0.2.0
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0
  firebase_messaging: ^16.6.0
  get: ^4.7.3
  ultralytics_yolo: ^0.6.14
  image: ^4.10.1
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  awesome_dialog: 3.3.0
  http: ^1.6.0
  google_sign_in: ^6.2.2
  qr_flutter: ^4.1.0
  flutter_blue_plus: ^2.3.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/best_float16.tflite
    - assets/models/labels.txt