name: hajicare
description: "Aplikasi pendamping ibadah haji dengan navigasi, komunikasi, dan keselamatan jamaah."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.2.1
  flutter_localizations:
    sdk: flutter
  vibration: ^3.2.1
  flutter_tts: ^4.2.2
  shared_preferences: ^2.5.5
  adhan: ^2.0.0+1
  flutter_compass: ^0.8.1
  geolocator: ^14.0.2
  hijri: ^3.0.1
  geocoding: ^5.0.0
  timezone: ^0.11.1
  lat_lng_to_timezone: ^0.2.0
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0
  get: ^4.7.3
  ultralytics_yolo: ^0.6.14
  image: ^4.10.1
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  http: ^1.6.0
  google_sign_in: ^7.2.0
  qr_flutter: ^4.1.0
  flutter_blue_plus: ^2.3.12
  mobile_scanner: ^7.4.2
  speech_to_text: ^7.4.0
  google_mlkit_translation: ^0.14.0
  flutter_onnxruntime: ^1.8.5
  url_launcher: ^6.3.2
  cloud_functions: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.jpeg"
  min_sdk_android: 21
  adaptive_icon_background: "#1E1A16"
  adaptive_icon_foreground: "assets/icon.jpeg"
  web:
    generate: true
    image_path: "assets/icon.jpeg"
    background_color: "#1E1A16"
    theme_color: "#D4AF37"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.jpeg
    - assets/models/best_float16.tflite
    - assets/models/labels.txt
    - assets/models/hajicare_encoder.onnx
    - assets/models/hajicare_prototypes.json
